config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # ↓ゲストログイン
  post '/guests/guest_sign_in', to: 'guests#new_guest'
  root to: 'homes#top'

  # ↓ナビゲーションページ
  get 'users/information' => "users#information", as: "information"
  get 'users/skill' => "users#skill", as: "skill"
  # ↓カット・カラー・パーマ
  resources :cuts, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :colors, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :perms, only: [:index, :show, :edit, :create, :update, :destroy]
  # カレンダー
  resources :blogs, only: [:index, :show, :edit, :create, :update, :destroy]
  # ↓お問い合わせ
  resources :contacts, only: [:create]
  get 'about' => "contacts#about", as: "contact_about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1, maximum: 15 }
  validates :content, presence: true, length: { minimum: 1, maximum: 200 }

  belongs_to :user
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :user
  attachment :color_image

  validates :title, presence: true, length: { minimum: 1, maximum: 20 }
  validates :detail, presence: true, length: { minimum: 1, maximum: 500 }
  validates :evaluation, presence: true
  validates :color_image, presence: true

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 15 }
  validates :email, presence: true, length: { minimum: 1, maximum: 50 }
  validates :phone_number, presence: true, length: { minimum: 9, maximum: 13 }
  validates :subject, presence: true, length: { minimum: 1, maximum: 11 }
  validates :message, presence: true, length: { minimum: 1, maxmum: 200 }
end

app/models/cut.rb
class Cut < ApplicationRecord
  belongs_to :user
  attachment :cut_image

  validates :title, presence: true, length: { minimum: 1, maximum: 20 }
  validates :detail, presence: true, length: { minimum: 1, maximum: 500 }
  validates :evaluation, presence: true
  validates :cut_image, presence: true

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/perm.rb
class Perm < ApplicationRecord
  belongs_to :user
  attachment :perm_image

  validates :title, presence: true, length: { minimum: 1, maximum: 20 }
  validates :detail, presence: true, length: { minimum: 1, maximun: 500 }
  validates :evaluation, presence: true
  validates :perm_image, presence: true

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :last_name,  presence: true, length: { minimum: 1, maximum: 20 }
  validates :phone_number, presence: true, length: { minimun: 9, maximum: 13 }
  has_many :blogs, dependent: :destroy
  has_many :cuts, dependent: :destroy
  has_many :colors, dependent: :destroy
  has_many :perms, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  def index
    @blogs = current_user.blogs
    @blog = Blog.new
  end

  def show
    @blog = current_user.blogs.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_parameter)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path, notice: "日程が追加されました"
    else
      @blogs = current_user.blogs
      render 'index'
    end
  end

  def destroy
    @blog = current_user.blogs.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "削除完了"
  end

  def edit
    @blog = current_user.blogs.find(params[:id])
  end

  def update
    @blog = current_user.blogs.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集完了"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :authenticate_user!
  def index
    @colors = current_user.colors.page(params[:page]).per(10).order('updated_at DESC').search(params[:search])
    @color = Color.new
  end

  def show
    @color = current_user.colors.find(params[:id])
  end

  def create
    @color = current_user.colors.new(color_parameter)
    if @color.save
      redirect_to colors_path, notice: "投稿完了"
    else
      @colors = current_user.colors.page(params[:page]).per(10).order('updated_at DESC')
      render 'index'
    end
  end

  def destroy
    @color = current_user.colors.find(params[:id])
    @color.destroy
    redirect_to colors_path, notice: "削除完了"
  end

  def edit
    @color = current_user.colors.find(params[:id])
  end

  def update
    @color = current_user.colors.find(params[:id])
    if @color.update(color_parameter)
      redirect_to colors_path, notice: "編集完了"
    else
      render 'edit'
    end
  end
end

private

def color_parameter
  params.require(:color).permit(:title, :detail, :evaluation, :color_image).merge(user_id: current_user.id)
end

app/controllers/cuts_controller.rb
class CutsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cuts = current_user.cuts.page(params[:page]).per(10).order('updated_at DESC').search(params[:search])
    @cut = Cut.new
  end

  def show
    @cut = current_user.cuts.find(params[:id])
  end

  def create
    @cut = current_user.cuts.new(cut_parameter)
    if @cut.save
      redirect_to cuts_path, notice: "投稿完了"
    else
      @cuts = current_user.cuts.page(params[:page]).per(10).order('updated_at DESC')
      render 'index'
    end
  end

  def destroy
    @cut = current_user.cuts.find(params[:id])
    @cut.destroy
    redirect_to cuts_path, notice: "削除完了"
  end

  def edit
    @cut = current_user.cuts.find(params[:id])
  end

  def update
    @cut = current_user.cuts.find(params[:id])
    if @cut.update(cut_parameter)
      redirect_to cuts_path, notice: "編集完了"
    else
      render 'edit'
    end
  end
end

private

def cut_parameter
  params.require(:cut).permit(:title, :detail, :evaluation, :cut_image).merge(user_id: current_user.id)
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/perms_controller.rb
class PermsController < ApplicationController
  before_action :authenticate_user!
  def index
    @perms = current_user.perms.page(params[:page]).per(10).order('updated_at DESC').search(params[:search])
    @perm = Perm.new
  end

  def show
    @perm = current_user.perms.find(params[:id])
  end

  def create
    @perm = current_user.perms.new(perm_parameter)
    if @perm.save
      redirect_to perms_path, notice: "投稿完了"
    else
      @perms = current_user.perms.page(params[:page]).per(10).order('updated_at DESC')
      render 'index'
    end
  end

  def destroy
    @perm = current_user.perms.find(params[:id])
    @perm.destroy
    redirect_to perms_path, notice: "削除完了"
  end

  def edit
    @perm = current_user.perms.find(params[:id])
  end

  def update
    @perm = current_user.perms.find(params[:id])
    if @perm.update(perm_parameter)
      redirect_to perms_path, notice: "編集完了"
    else
      render 'edit'
    end
  end
end

private

def perm_parameter
  params.require(:perm).permit(:title, :detail, :evaluation, :perm_image).merge(user_id: current_user.id)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def information
  end

  def skill
  end
end

private

def user_params
  params.require(:user).permit(:first_name, :last_name, :phone_number)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/color_helper.rb
module ColorHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cut_helper.rb
module CutHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/perm_helper.rb
module PermHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
  <div class="calendar">
    <%= form_with(model: @blog, local: true) do |form| %>
      <div class="taitoru">
        <div class="form-tag">タイトル</div>
        <%= form.text_field :title %>
      </div>

      <div class="naiyou">
        <div class="form-tag">内容</div>
        <%= form.text_field :content %>
      </div>

      <div class="time">
        <div class="form-tag">時間</div>
        <%= form.datetime_select :start_time %>
      </div>

      <div class="submit">
        <%= form.submit "編集",class:"nice_btn" %>
      </div>
    <% end %>
  </div>

app/views/blogs/index.html.erb
 <!--------このページはbootstrapを主に使用しています------->
  <div class="calendar">
  <h1 class="calendar_top">カレンダー</h1>
  <br>
  <h5 class="mt-2">ログイン:<span class="text-info"><%= current_user.last_name %></span>様</h5>
    <div class="blog_page_row">
      <div class="col-md-3">

      <% if @blog.errors.any? %>
        <% @blog.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <div class="touko">
        <%= form_with(model: @blog, local: true) do |form| %>
          <div class="title">
            <div class="form-tag mt-5">タイトル</div>
            <%= form.text_field :title, placeholder: "1~15文字", class: "form-control blog_form" %>
          </div>

          <div class="detail">
            <div class="form-tag">内容</div>
            <%= form.text_area :content, size: '30x10', placeholder: "1~200文字", class: "form-control blog_form" %>
          </div>

          <div class="time">
            <div class="form-tag">時間</div>
            <%= form.datetime_select :start_time %>
          </div>
          <div class="submit">
            <p>スケジュールを投稿しますか？</p>
            <%= form.submit "投稿する" %>
          </div>
        <% end %>
        </div>
      </div>

      <br>

      <div class="col-md-9 mb-5">
        <div class="bg-dark text-white mb-5">今後の予定一覧</div>
        <%= month_calendar events: @blogs do |date, blogs| %>
          <%= date.day %>

          <% blogs.each do |blog| %>
            <div>
                <%= link_to blog.title,blog_path(blog.id) %>
            </div>
          <% end %>
        <% end %>
      </table>
      </div>
    </div>
  </div>

app/views/blogs/show.html.erb
  <!--このページはbootstrapを主に使用しています-->
  <div class="calendar">
    <div class="show">
      <div class="blog-page-text-back">
        <h3 class="text-success pt-3">タイトル</h3></br>
        <h4 class="text-white"><%= @blog.title %></h4>

        <h3 class="text-success pt-3">内容</h3></br>
        <h4 class="text-white"><%= @blog.content %></h4>

        <h3 class="text-success pt-3">予定日</h3></br>
        <h4 class="text-white"><%= @blog.start_time.strftime("%m-%d") %></h4>

        <h3 class="text-success pt-3">予定時間</h3></br>
        <h4 class="text-white"><%= @blog.start_time.strftime("%H:%M") %></h4>

        <h3 class="text-success pt-3">予定を作成した日</h3></br>
        <h4 class="text-white"><%= @blog.created_at.strftime('%Y/%m/%d') %></h4>

        <h3 class="text-success pt-3">予定を作成した時間</h3></br>
        <h4 class="text-white"><%= @blog.created_at.strftime('%H:%M') %></h4>
      </div>
      <p>
        <h3 class="text-info">終了した予定は削除しましょう</h3>
      </p>

      <%= link_to '編集', edit_blog_path(@blog), class: "btn btn-primary m-4" %>
      <%= link_to '消去',blog_path(@blog.id), class: "btn btn-danger m-4", method: :delete, data: { confirm: '本当に削除しますか?（失われたデータは元には戻りません）' } %>
      <%= link_to '戻る', blogs_path, class: "btn btn-dark m-4" %>
    </div>
  </div>

app/views/colors/edit.html.erb
  <div class="skill_page_zone">
    <div class="edit">
    <%= form_with(model: @color, local: true) do |form| %>
      <div class="daimei">
        <h3 class="skill_column_title_detail_evaluation pt-3">タイトル</h3></br>
        <%= form.text_field :title %>
      </div>

      <div class="detail">
        <h3 class="skill_column_title_detail_evaluation pt-3">詳細</h3></br>
        <%= form.text_field :detail %>
      </div>

      <div class="evaluation">
        <h3 class="skill_column_title_detail_evaluation pt-3"></h3>
        <%= form.number_field :evaluation %>
      </div>

      <div class="submit">
        <%= form.submit "編集", class:"nice_btn" %>
        <% end %>
        <%= link_to '戻る', colors_path, class: "btn btn-dark m-4" %>
      </div>
    </div>
  </div>

app/views/colors/index.html.erb
  <!--このページはbootstrapを主に使用しています-->
  <div class="color_page_zone">
    <div class="index">
      <h1 class="color">カラー</h1>
      <br>
      <div class="skill_zone_row">
        <div class="col-md-4 skill_form_text">

          <% if @color.errors.any? %>
            <% @color.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          <% end %>

          <div class="touko">
            <%= form_with(model: @color, local: true) do |form| %>
              <div class="title">
                <div class="form-tag">タイトル</div>
                <%= form.text_field :title, placeholder: "1~20文字", class: "form-control" %>
              </div>

              <div class="detail">
                <div class="form-tag">詳細</div>
                <%= form.text_area :detail, size: '30x10', placeholder: "1~500文字", class: "form-control color_form" %>
              </div>

              <div>
                <div class="form-tag">自己評価点数</div>
                <%= form.number_field :evaluation, placeholder: "数字入力", class: "color_form" %>
              </div>
            <p>
              <div class="title">
                <div class="form-tag">写真</div>
                <%= form.attachment_field :color_image %>
              </div>
            </p>
              <div class="submit">
                <%= form.submit %>
              </div>
            <% end %>
          </div>
        </div>
        <br>

        <div class="col-md-8">
          <div class="color_index">カラーテーブル</div>
            <div class="kensaku">
            <%= form_tag(colors_path,:method => "get") do %>
            <%= text_field_tag :search %>
            <%= submit_tag "Search" ,:title => nil,class: "button is-info"%>
            <% end %>
            <% @colors %>
            <%= link_to '戻す', colors_path, class: "btn btn-dark ml-1" %>
            </div>
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th>タイトル</th>
                  <th>投稿日時</th>
                </tr>
              </thead>
              <tbody>
                <% @colors.each do |color| %>
                  <tr class="text-warning bg-white">
                    <td><%= link_to color.title,color_path(color.id) %></td>
                    <td><%= color.created_at.strftime('%Y/%m/%d %H:%M') %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <div class="ml-5"><%= paginate @colors %></div>
        </div>
      </div>
    </div>
  </div>

app/views/colors/show.html.erb
  <div class="color_page_zone">
    <div class="color_page_text_back">
        <h3 class="skill_column_title_detail_evaluation pt-3">タイトル</h3></br>
        <h3 class="skill_record_title_detail_evaluation"><%= @color.title %></h4>
        <h3 class="skill_column_title_detail_evaluation pt-3">詳細</h4><br>
        <h5 class="skill_record_title_detail_evaluation"><%= @color.detail %></h5>
        <h3 class="skill_column_title_detail_evaluation pt-3">評価</h3>
        <h5 class="skill_record_title_detail_evaluation"><%= @color.evaluation %></h5>
        <br>
      </div>
      <%=link_to Refile.attachment_url(@color, :color_image), "data-lightbox" => @color.id do %>
        <%= attachment_image_tag @color, :color_image , class: 'd-block mx-auto cut-img mt-4' %>
      <% end %>
      <div class="skill_edit_delete_back">
      <%= link_to '編集', edit_color_path(@color), class: "btn btn-primary m-4" %>
      <%= link_to '消去',color_path(@color.id), class: "btn btn-danger m-4", method: :delete, data: { confirm: '本当に削除しますか?（失われたデータは元には戻りません）' } %>
      <%= link_to '戻る', colors_path, class: "btn btn-dark m-4" %>
      </div>
    </div>
  </div>

app/views/cuts/edit.html.erb
  <div class="cut_page_zone">
    <div class="edit">
    <%= form_with(model: @cut, local: true) do |form| %>
      <div class="daimei">
        <h3 class="skill_column_title_detail_evaluation pt-3">タイトル</h3></br>
        <%= form.text_field :title %>
      </div>
      <div class="detail">
        <h3 class="skill_column_title_detail_evaluation pt-3">詳細</h3></br>
        <%= form.text_field :detail %>
      </div>

      <div class="evaluation">
        <h3 class="skill_column_title_detail_evaluation pt-3">評価</h3>
        <%= form.number_field :evaluation %>
      </div>

      <div class="submit">
        <%= form.submit "編集", class:"nice_btn" %>
        <% end %>
        <%= link_to '戻る', cuts_path, class: "btn btn-dark m-4" %>
      </div>
    </div>
  </div>

app/views/cuts/index.html.erb
  <!------このページはbootstrapを主に使用しています-------->
  <div class="cut_page_zone">
    <div class="index">
      <h1 class="cut">カット</h1>
      <br>
      <div class="skill_zone_row">
        <div class="col-md-4 skill_form_text">

          <% if @cut.errors.any? %>
            <% @cut.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          <% end %>

           <div class="touko">
             <%= form_with(model: @cut, local: true) do |form| %>
              <div class="title">
                <div class="form-tag">タイトル</div>
                <%= form.text_field :title, placeholder: "1~20文字", class: "form-control cut_form" %>
              </div>

              <div class="detail">
                <div class="form-tag">詳細</div>
                <%= form.text_area :detail, size: '30x10', placeholder: "1~500文字", class: "form-control cut_form" %>
              </div>

              <div>
                <div class="form-tag">自己評価点数</div>
                <%= form.number_field :evaluation, placeholder: "数字入力", class: "cut_form" %>
              </div>
            <p>
              <div class="picture">
                <div class="form-tag">写真</div>
                <%= form.attachment_field :cut_image %>
              </div>
            </p>
              <div class="submit">
                <%= form.submit %>
              </div>
            <% end %>
          </div>
        </div>
        <br>

        <div class="col-md-8">
          <div class="cut_index">カットテーブル</div>
            <div class="kensaku">
              <%= form_tag(cuts_path,:method => "get") do %>
              <%= text_field_tag :search %>
              <%= submit_tag "Search" ,:title => nil,class: "button is-info"%>
              <% end %>
              <% @cuts %>
              <%= link_to '戻す', cuts_path, class: "btn btn-dark ml-1" %>
            </div>
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th>タイトル</th>
                  <th>投稿日時</th>
                </tr>
              </thead>
              <tbody>
                <% @cuts.each do |cut| %>
                  <tr class="text-warning bg-white">
                    <td><%= link_to cut.title,cut_path(cut.id) %></td>
                    <td><%= cut.created_at.strftime('%Y/%m/%d %H:%M') %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <div class="ml-5"><%= paginate @cuts %></div>
        </div>
      </div>
    </div>
  </div>

app/views/cuts/show.html.erb
  <div class="cut_page_zone">
    <div class="show">
      <div class="cut_page_text_back">
        <h3 class="skill_column_title_detail_evaluation pt-3">タイトル</h3></br>
        <h3 class="skill_record_title_detail_evaluation"><%= @cut.title %></h4>
        <h3 class="skill_column_title_detail_evaluation pt-3">詳細</h4><br>
        <h5 class="skill_record_title_detail_evaluation"><%= @cut.detail %></h5>
        <h3 class="skill_column_title_detail_evaluation pt-3">評価</h3>
        <h5 class="skill_record_title_detail_evaluation"><%= @cut.evaluation %></h5>
        <br>
      </div>
      <%=link_to Refile.attachment_url(@cut, :cut_image), "data-lightbox" => @cut.id do %>
        <%= attachment_image_tag @cut, :cut_image , class: 'd-block mx-auto cut-img mt-4' %>
      <% end %>
      <div class="skill_edit_delete_back">
      <%= link_to '編集', edit_cut_path(@cut), class: "btn btn-primary m-4" %>
      <%= link_to '消去',cut_path(@cut.id), class: "btn btn-danger m-4", method: :delete, data: { confirm: '本当に削除しますか?（失われたデータは元には戻りません）' } %>
      <%= link_to '戻る', cuts_path, class: "btn btn-dark m-4" %>
      </div>
    </div>
  </div>

app/views/perms/edit.html.erb
  <div class="perm_page_zone">
    <div class="edit">
      <%= form_with(model: @perm, local: true) do |form| %>
      <div class="daimei">
        <h3 class="skill_column_title_detail_evaluation pt-3">タイトル</h3></br>
        <%= form.text_field :title %>
      </div>
      <div class="detail">
        <h3 class="skill_column_title_detail_evaluation pt-3">詳細</h3></br>
        <%= form.text_field :detail %>
      </div>

      <div class="evaluation">
        <h3 class="skill_column_title_detail_evaluation pt-3">評価</h3></br>
        <%= form.number_field :evaluation %>
      </div>

      <div class="submit">
        <%= form.submit "編集", class:"nice_btn" %>
        <% end %>
        <%= link_to '戻る', perms_path, class: "btn btn-dark m-4" %>
      </div>
    </div>
  </div>

app/views/perms/index.html.erb
  <!--このページはbootstrapを主に使用しています------------>

  <div class="perm_page_zone">
    <div class="index">
      <h1 class="perm">パーマ</h1>
      <br>
      <div class="skill_zone_row">
        <div class="col-md-4 skill_form_text">

          <% if @perm.errors.any? %>
            <% @perm.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
          <% end %>

          <div class="touko">
            <%= form_with(model: @perm, local: true) do |form| %>
              <div class="title">
                <div class="form-tag">タイトル</div>
                <%= form.text_field :title, placeholder: "1~20文字", class: "form-control perm_form" %>
              </div>

              <div class="detail">
                <div class="form-tag">詳細</div>
                <%= form.text_area :detail, size: '30x10', placeholder: "1~500文字", class: "form-control perm_form" %>
              </div>

              <div>
                <div class="form-tag">自己評価点数</div>
                <%= form.number_field :evaluation, placeholder: "数字入力", class: "perm_form" %>
              </div>
            <p>
              <div class="detail">
                <div class="form-tag">写真</div>
                <%= form.attachment_field :perm_image %>
              </div>
            </p>
              <div class="submit">
                <%= form.submit %>
              </div>
            <% end %>
          </div>
        </div>

        <br>

        <div class="col-md-8">
          <div class="perm_index">パーマテーブル</div>
          <!--検索--->
        <div class="kensaku">
          <%= form_tag(perms_path,:method => "get") do %>
          <%= text_field_tag :search %>
          <%= submit_tag "Search" ,:title => nil,class: "button is-info"%>
          <% end %>
          <% @perms %>
          <%= link_to '戻す', perms_path, class: "btn btn-dark ml-1" %>
        </div>
          <div class="ml-5"><%= paginate @perms %></div>
            <table class="table ml-2">
              <thead class="thead-dark">
                <tr>
                  <th>タイトル</th>
                  <th>投稿日時</th>
                </tr>
              </thead>
              <tbody>
                <% @perms.each do |perm| %>
                  <tr class="text-warning bg-white">
                      <td><%= link_to perm.title,perm_path(perm.id) %></td>
                      <td><%= perm.created_at.strftime('%Y/%m/%d %H:%M') %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <div class="ml-5"><%= paginate @perms %></div>
        </div>
      </div>
    </div>
  </div>

app/views/perms/show.html.erb
<div class="perm_page_zone">
  <div class="show">
    <div class="perm_page_text_back">
        <h3 class="skill_column_title_detail_evaluation pt-3">タイトル</h3></br>
        <h3 class="skill_record_title_detail_evaluation"><%= @perm.title %></h4>
        <h3 class="skill_column_title_detail_evaluation pt-3">詳細</h4><br>
        <h5 class="skill_record_title_detail_evaluation"><%= @perm.detail %></h5>
        <h3 class="skill_column_title_detail_evaluation pt-3">評価</h3>
        <h5 class="skill_record_title_detail_evaluation"><%= @perm.evaluation %></h5>
        <br>
      </div>
      <%=link_to Refile.attachment_url(@perm, :perm_image), "data-lightbox" => @perm.id do %>
        <%= attachment_image_tag @perm, :perm_image , class: 'd-block mx-auto cut-img mt-4' %>
      <% end %>
      <div class="skill_edit_delete_back">
      <%= link_to '編集', edit_perm_path(@perm), class: "btn btn-primary m-4" %>
      <%= link_to '消去',perm_path(@perm.id), class: "btn btn-danger m-4", method: :delete, data: { confirm: '本当に削除しますか?（失われたデータは元には戻りません）' } %>
      <%= link_to '戻る', perms_path, class: "btn btn-dark m-4" %>
      </div>
  </div>
</div>

app/views/users/information.html.erb
<div class="information_page_zone">

  <h2 class="information_title">HairSkill</h2>

  <div id="arrow-left" class="arrow"></div>
  <div id="arrow-right" class="arrow"></div>

  <div id="slider">
    <div class="slide slide1"></div>
    <div class="slide slide2"></div>
    <div class="slide slide3"></div>
  </div>

  <h3 class="blink">おみくじを引いてみよう⬇︎</h3>
  <input id="omikuji_btn" type="button" value="おみくじを引く">
</div>

app/views/users/skill.html.erb
  <!--cssはusers.cssに記述しています-->
  <div class="skill_navigation_page">
    <ul class="skill_navigation_zone">
      <%= link_to cuts_path, class:"skill_seni" do %>
        <li class="skill_navigation_cut">
          <span>Cut</span>
        </li>
      <% end %>
      <%= link_to colors_path, class:"skill_seni" do %>
        <li class="skill_navigation_color">
          <span>Color</span>
        </li>
      <% end %>
      <%= link_to perms_path, class:"skill_seni" do %>
        <li class="skill_navigation_perm">
          <span>Perm</span>
        </li>
      <% end %>
    </ul>
    <h4 class="timer-moji">Timer</h4>
    <div id="timer">00:00:000</div>
    <div id="time_control">
      <p id="start">start</p>
      <p id="stop">stop</p>
      <p id="reset">reset</p>
    </div>
  </div>