config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # ↓ゲストログイン
  post '/guests/guest_sign_in', to: 'guests#new_guest'
  root to: 'homes#top'

  # ↓ナビゲーションページ
  get 'users/information' => "users#information", as: "information"
  get 'users/skill' => "users#skill", as: "skill"
  # ↓カット・カラー・パーマ
  resources :cuts, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :colors, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :perms, only: [:index, :show, :edit, :create, :update, :destroy]
  # カレンダー
  resources :blogs, only: [:index, :show, :edit, :create, :update, :destroy]
  # ↓お問い合わせ
  resources :contacts, only: [:create]
  get 'about' => "contacts#about", as: "contact_about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1, maximum: 15 }
  validates :content, presence: true, length: { minimum: 1, maximum: 200 }

  belongs_to :user
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :user
  attachment :color_image

  validates :title, presence: true, length: { minimum: 1, maximum: 20 }
  validates :detail, presence: true, length: { minimum: 1, maximum: 500 }
  validates :evaluation, presence: true
  validates :color_image, presence: true

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 15 }
  validates :email, presence: true, length: { minimum: 1, maximum: 50 }
  validates :phone_number, presence: true, length: { minimum: 9, maximum: 13 }
  validates :subject, presence: true, length: { minimum: 1, maximum: 11 }
  validates :message, presence: true, length: { minimum: 1, maxmum: 200 }
end

app/models/cut.rb
class Cut < ApplicationRecord
  belongs_to :user
  attachment :cut_image

  validates :title, presence: true, length: { minimum: 1, maximum: 20 }
  validates :detail, presence: true, length: { minimum: 1, maximum: 500 }
  validates :evaluation, presence: true
  validates :cut_image, presence: true

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/perm.rb
class Perm < ApplicationRecord
  belongs_to :user
  attachment :perm_image

  validates :title, presence: true, length: { minimum: 1, maximum: 20 }
  validates :detail, presence: true, length: { minimum: 1, maximun: 500 }
  validates :evaluation, presence: true
  validates :perm_image, presence: true

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :last_name,  presence: true, length: { minimum: 1, maximum: 20 }
  validates :phone_number, presence: true, length: { minimun: 9, maximum: 13 }
  has_many :blogs, dependent: :destroy
  has_many :cuts, dependent: :destroy
  has_many :colors, dependent: :destroy
  has_many :perms, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  def index
    @blogs = current_user.blogs
    @blog = Blog.new
  end

  def show
    @blog = current_user.blogs.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_parameter)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path, notice: "日程が追加されました"
    else
      @blogs = current_user.blogs
      render 'index'
    end
  end

  def destroy
    @blog = current_user.blogs.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "削除完了"
  end

  def edit
    @blog = current_user.blogs.find(params[:id])
  end

  def update
    @blog = current_user.blogs.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集完了"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/cuts_controller.rb
class CutsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cuts = current_user.cuts.page(params[:page]).per(10).order('updated_at DESC').search(params[:search])
    @cut = Cut.new
  end

  def show
    @cut = current_user.cuts.find(params[:id])
  end

  def create
    @cut = current_user.cuts.new(cut_parameter)
    if @cut.save
      redirect_to cuts_path, notice: "投稿完了"
    else
      @cuts = current_user.cuts.page(params[:page]).per(10).order('updated_at DESC')
      render 'index'
    end
  end

  def destroy
    @cut = current_user.cuts.find(params[:id])
    @cut.destroy
    redirect_to cuts_path, notice: "削除完了"
  end

  def edit
    @cut = current_user.cuts.find(params[:id])
  end

  def update
    @cut = current_user.cuts.find(params[:id])
    if @cut.update(cut_parameter)
      redirect_to cuts_path, notice: "編集完了"
    else
      render 'edit'
    end
  end
end

private

def cut_parameter
  params.require(:cut).permit(:title, :detail, :evaluation, :cut_image).merge(user_id: current_user.id)
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/color_helper.rb
module ColorHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cut_helper.rb
module CutHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/perm_helper.rb
module PermHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HairSkill</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript">
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>

      <div class="header">
        <%= link_to root_path do %>
          <span class="header_logo"><h1 class="theme_title">HairSkill</h1></span>
        <% end %>

        <nav class="header_nav">
          <ul>
            <!--↓もしログインしていたら-->
            <% if user_signed_in? %>
              <li class="">
                <%= link_to skill_path, class:"h-seni" do %>
                  <span>技術</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to information_path, class:"h-seni" do %>
                  <span>情報</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to blogs_path, class:"h-seni" do %>
                  <span>カレンダー</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to contact_about_path, class:"h-seni" do %>
                  <span>連絡</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to edit_user_registration_path, class:"h-seni" do %>
                  <span>変更</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to destroy_user_session_path, method: :delete, id: "header-logout-link", class:"h-seni" do %>
                  <span>退出</span>
                <% end %>
              </li>
            <!--↓もしログインしていなかったら-->
            <% else %>
              <li class="">
                <%= link_to guests_guest_sign_in_path, method: :post, class:"h-seni" do %>
                  <span>ゲストログイン</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_registration_path, class:"h-seni" do %>
                  <span>新規登録</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_session_path, class:"h-seni" do %>
                  <span>参加</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to contact_about_path, class:"h-seni" do %>
                  <span>連絡</span>
                <% end %>
              </li>
              <% end %>
            </ul>
        </nav>
      </div>
    <% if flash[:notice] %>
      <div class="good">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <%= yield %>
    <div class=footer>
      <nav class="footer_nav">
          <ul>
            <!--スマホの時ナビをfooterに表示-->
            <!--↓もしログインしていたら-->
            <% if user_signed_in? %>

              <li class="">
                <%= link_to skill_path, class:"f-seni" do %>
                  <span class="fas fa-seedling" style="display: block;"></span>
                  <span class="hurigana">技術</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to information_path, class:"f-seni" do %>
                  <span class="fas fa-info-circle" style="display: block;"></span>
                  <span class="hurigana">情報</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to blogs_path, class:"f-seni" do %>
                  <span class="fas fa-calendar-alt" style="display: block;"></span>
                  <span class="hurigana">日程</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to contact_about_path, class:"f-seni" do %>
                  <span class="far fa-envelope" style="display: block;"></span>
                  <span class="hurigana">連絡</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to edit_user_registration_path, class:"f-seni" do %>
                  <span class="fas fa-user-cog" style="display: block;"></span>
                  <span class="hurigana">変更</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to destroy_user_session_path, method: :delete, id: "footer-logout-link", class:"f-seni" do %>
                  <span class="fas fa-sign-out-alt" style="display: block;"></span>
                  <span class="hurigana">退出</span>
                <% end %>
              </li>
            <!--↓もしログインしていなかったら-->
            <% else %>
              <li class="">
                <%= link_to guests_guest_sign_in_path, method: :post, class:"f-seni" do %>
                  <span class="fas fa-user-shield" style="display: block;"></span>
                  <span>ゲスト</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_registration_path, class:"f-seni" do %>
                  <span class="fas fa-user-shield" style="display: block;"></span>
                  <span class="hurigana">新規</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to new_user_session_path, class:"f-seni" do %>
                  <span class="fas fa-sign-in-alt" style="display: block;"></span>
                  <span class="hurigana">参加</span>
                <% end %>
              </li>
              <li class="">
                <%= link_to contact_about_path, class:"f-seni" do %>
                  <span class="far fa-envelope" style="display: block;"></span>
                  <span class="hurigana">連絡</span>
                <% end %>
              </li>
              <% end %>
            </ul>
        </nav>
    </div>

  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>